# Generated by Django 3.2.9 on 2021-11-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20211105_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='modification_date',
        ),
    ]
