# Generated by Django 3.2.9 on 2021-11-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='', upload_to='movie/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(default='', upload_to='movie/videos'),
            preserve_default=False,
        ),
    ]
